language: java
sudo: false
jdk:
- openjdk11
env:
  global:
  - secure: "SvqhJ7cFF4Uir0rvngiZAsxhgYAFCdw1bVHfKtA2MAV5taAuGsN0Uij+kLUP0oxHmrKwbSoOlHmTOG6m6GYOmX9ALAgfVRI41vnZxzhhR6zdHq4Kx84rhIxGHAXhxY8GPJiN+ClyeEr/qf6Jb60XyydU7w1wO8a1y+AYSW/CK0HZ4qORVgHOmfMmP7sCmgaPwCCcNoq/5mW873XHbJUbVh4d0wNn6Pej9oKRgsShWCqb/ihQ4IqNQjSQO+nF9FAuqMVzFJhnoNempuHG6R98QUlHXZ4IERlYfWfwjg6OtXk369QMAbQQ3k8bheozgM7R1mRq/cfIyIWzqY29UjqGVChy918QvXLDpLtVeU8ThF5cPgsle8K2NdaHZutfYXFo7qVosIAAMwkory5WN+RX7W2DqXAFwZjn5SfHvPMTz3tFgvAfVkV3qQg/bdOI6vA1cLghd/ZPRiCoJVJ/EdxwDor/FH5wRW2XFPIkqSWjlv4TnAd8YoAUZ44iO0DyUgyrB6oVdNYhW+0ei0M181rkSLdg5yfDykQF324lIwMwoalDMK4LcTxcgFVdyLSZr0xVtJr9vmr3w2xoJfB18hufHKkqMZQ+kDlhAmAjZApmrAIRR22gqhJJNctTEbX4O2s2BbD93TuKhBQMMDYzfoM8s62NCQ3qUbPtQUECW5HbF+k=" # CODACY_PROJECT_TOKEN
  - secure: "JrrO+ToZ5UPkT95mNnzX9XmunVO3zIc8s6c7MMDFpBciA/hyaYmK1R4vsyCudiZtuu7VvSmK31YRoxphwWfAD+eEsvjWMMgT0MDz3eOMkI+0/XrFf2Lh9cJ4Ow0OfHvu3w51FGAuf59ZCuA6KlYhJEThRXf8Sp31ecuZRu0CWHDRfXp5+tyARu7Ly0XScy/DNnjSbKOeKKZ28PH6/ZxIptWMk5GLQtnaUCesv4Z3Lg31WsPGkqlDPyXH4P4TF9ttOKpk6Nw4rTzgprOe30ULlT7AuQRQ1KFbHBJe8vKD0mCIPlfir0yr1fFjX8S+wwEDVuCnLRiNUH+HWLOkcUlAlE+Oif0a7bjHNcQH0Y26aLQoOMhzR8lAj0HTk0fIDXXA9JGVOdDetGxHkjxY87Op4gh54WO3HheNO4Tw7RoBGdKy1qSa9bafKr2aGeQrACCMKqZxj0ZepdmfPIuo1uiYPFec3/hXeMMx2a0Qaj5wRrtYvWgrp8UVgT2MJ1L16/dsc77xv815CSoco83Z4cEhILOTAXrQxCzc5B6h725NpfLkoBJSjjbW1JQplWohbYYUvQfwLRIuvlH5ickCpwWNofgXsZBOViXeea6zaJwhezgfUfOR3sXEblQS65gFIOOUcz+BOL2ZYpjmPZ3h7ZPOPM8nXVc1M/zlwCb2BIeD3L0=" # BINTRAY_API_KEY
install:
- curl -o $HOME/.m2/settings.xml https://gist.githubusercontent.com/cryptobot/cf5fbd909c4782aaeeeb7c7f4a1a43da/raw/fb3fe9a6db00cdac09788285b108a3645193a45b/settings.xml
- mvn dependency:go-offline -Pdependency-check,coverage,release
script:
- mvn clean test jacoco:report verify -Dsurefire.useFile=false -Pcoverage
after_success:
- curl -o ~/codacy-coverage-reporter.jar https://repo.maven.apache.org/maven2/com/codacy/codacy-coverage-reporter/7.1.0/codacy-coverage-reporter-7.1.0-assembly.jar
- $JAVA_HOME/bin/java -jar ~/codacy-coverage-reporter.jar report -l Java -r target/site/jacoco/jacoco.xml
cache:
  directories:
  - $HOME/.m2
deploy:
- provider: script # RELEASES
  script: mvn clean versions:set -DnewVersion=${TRAVIS_TAG} deploy -DskipTests -Prelease
  skip_cleanup: true
  on:
    repo: cryptomator/fuse-nio-adapter
    tags: true
after_deploy:
  - "echo '{\"close\": \"1\"}' | curl --max-time 10 -X POST -u cryptobot:${BINTRAY_API_KEY} https://api.bintray.com/maven_central_sync/cryptomator/maven/fuse-nio-adapter/versions/${TRAVIS_TAG}"
