baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.de]
    weight = 2
    languageName = "Deutsch"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

[markup.goldmark.renderer]
unsafe = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.5.3"
      filename = "Cryptomator-1.5.3-x64.exe"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.3/Cryptomator-1.5.3-x64.exe"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.3/Cryptomator-1.5.3-x64.exe.asc"
      checksum = "290506bedf4acd3950a40068346d8e706e4f16c885e6c42d4eafd70cbf829eea"
    [params.releases.dmg]
      version = "1.5.3"
      filename = "Cryptomator-1.5.3.dmg"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.3/Cryptomator-1.5.3.dmg"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.3/Cryptomator-1.5.3.dmg.asc"
      checksum = "cff42fe249b44fe8971af4eeabc1ca553b0c60345d2878d9cdbd474a5b17bc9e"
    [params.releases.appimage]
      version = "1.5.3"
      filename = "cryptomator-1.5.3-x86_64.AppImage"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.3/cryptomator-1.5.3-x86_64.AppImage"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.3/cryptomator-1.5.3-x86_64.AppImage.asc"
      checksum = "681551cc1539d2cdaa683286d0d528ffcb3027cb3524b6a2918ef7b51c0abffa"
    [params.releases.android]
      version = "1.5.2"
      filename = "Cryptomator-1.5.2.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.5.2/Cryptomator-1.5.2.apk"
      checksum = "834ec1410e4ed0769ebffdd0d8f352661d429de8696d51217d170729a089b0b7"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
