# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: source/conf.py

# Build all formats
formats:
  - epub
  - pdf

# Sets the version of Python and requirements required to build docs
python:
  version: 3.8
  install:
    - requirements: requirements.txt

# Add the files of the specified submodules to the build process
submodules:
  include: all